### ISSUE TITLE
MAC counts

### ISSUE THREAD

**Issue by marmoi** [oxmlsys/tflite-tools#5]
Hi,
I found this code very useful, thanks for sharing it. 
While run it for my model I wanted to calculate the number of macs, and eventhough I set the parameter to True it still didn't show up anything. I made a small modification of the script "tflite_model.py" in the function "_execution_schedule_info"
Before:
`macs = self._macs_for_op(op) if macs else 0`
Modified:
`macs_val = self._macs_for_op(op) if macs else 0`

So the variable _macs_ does not get overwrite, and now it shows the macs count.

**Comment by eliberis** [comment]
Thanks for this! Fixed
